spice_mix = set()
print(f"Initial spice mix values: {spice_mix}")
print(f"Initial spice mix id: {id(spice_mix)}")
spice_mix.add("Ginger")
spice_mix.add("Cardamon")
print(f"Now spice mix values: {spice_mix}")
print(f"Now spice mix id : {id(spice_mix)}")
